#!/bin/bash -u

DISTROOT=~/work/EDPM

TOYCORPUS=.
cachedir=$TOYCORPUS/cache

# verbose="--verbose";
verbose="";

mkdir -p $cachedir

# ONE REFERENCE
mkdir -p $TOYCORPUS/1ref
$DISTROOT/scripts/wrap-mteval $TOYCORPUS/system01.sgm \
    > $TOYCORPUS/1ref/system01.xml
$DISTROOT/scripts/wrap-mteval $TOYCORPUS/reference01.sgm \
    > $TOYCORPUS/1ref/reference01.xml
$DISTROOT/scripts/score-MetricsMATR --verbose \
    --outdir $TOYCORPUS/1ref \
    --cachedir $cachedir \
    --translation $TOYCORPUS/1ref/system01.xml \
    --reference $TOYCORPUS/1ref/reference01.xml

# TWO REFERENCES
mkdir -p $TOYCORPUS/2ref
$DISTROOT/scripts/wrap-mteval $TOYCORPUS/system01.sgm \
    > $TOYCORPUS/2ref/system01.xml
$DISTROOT/scripts/wrap-mteval \
    $TOYCORPUS/reference01.sgm $TOYCORPUS/reference02.sgm \
    > $TOYCORPUS/2ref/reference01-reference02.xml

$DISTROOT/scripts/score-MetricsMATR --verbose \
    --outdir $TOYCORPUS/2ref \
    --cachedir $cachedir \
    --translation $TOYCORPUS/2ref/system01.xml \
    --reference $TOYCORPUS/2ref/reference01-reference02.xml

echo "results in $TOYCORPUS/1ref $TOYCORPUS/2ref ;  cache in $cachedir" 1>&2;